### ISSUE TITLE
get error code when using result.summary()

### ISSUE THREAD

**Issue by chenkuangqi** [lod531/regPyHDFE#1]
developed 2 cluster_ids, get

IndexError:: boolean index did not match indexed array along dimension 1; dimension is 1 but corresponding boolean dimension is 2

when running: 
`line 172:in_cluster = (ID==c_list[c])`

**Comment by lod531** [comment]
Hey, You should try using https://github.com/lod531/FixedEffectModel
It's basically a better version of this repo

**Comment by chenkuangqi** [comment]
> 

Thank you so much for your quick reply! Do you know if there is any package support weight function as in Stata?

**Comment by lod531** [comment]
Hmm, sorry I wrote this two years ago, so I can't say. I'd check out https://github.com/ksecology/FixedEffectModel which is what I forked forever ago - at the time they seemed to have one of the better implementations, so the functionality might be there

**Comment by chenkuangqi** [comment]
Thank you so much. I really appreciate your help.

**Comment by lod531** [comment]
Haha, sorry I couldn't be of more use. Good luck!
